resources:
  - ./../../base
  - hpa.yml
  - ingress.yml

patches:
  - target:
      kind: Deployment
      labelSelector: "manifest_type=api"
    path: patches/resources.yml





# resources:
#   - ./../../base
#   - hpa.yml
#   - ingress.yml

# patches:
#   - target:
#       kind: Deployment
#       labelSelector: "manifest_type=api"
#     path: patches/resources.yml

#   - target:
#       kind: Deployment
#       labelSelector: "manifest_type=comms-cron"
#     path: patches/comms-resources.yml

