apiVersion: v1
kind: Service
metadata:
  name: ${{ values.application_name }}-svc
  labels:
    app: ${{ values.application_name }}-svc
    manifest_type: svc
spec:
  selector:
    app: ${{ values.application_name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8000
